
scrape_configs:
- job_name: minio-job
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: [storage:9000]

- job_name: uploader-job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [uploader:3000]

- job_name: security-job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [security:3000]