
version: '3.3'

networks:
  network_redis_cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.24.0.0/8

volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}

services:
  redis_1:
    image: redis:7.2
    restart: always
    container_name: redis_1
    ports:
      - 6381:6379
      - 16381:16381
    networks:
      network_redis_cluster:
        ipv4_address: 173.24.0.1
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - redis_1_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis_2:
    image: redis:7.2
    restart: always
    container_name: redis_2
    ports:
      - 6382:6379
      - 16382:16382
    networks:
      network_redis_cluster:
        ipv4_address: 173.24.0.2
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - redis_2_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis_3:
    image: redis:7.2
    restart: always
    container_name: redis_3
    ports:
      - 6383:6379
      - 16383:16381
    networks:
      network_redis_cluster:
        ipv4_address: 173.24.0.3
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - redis_3_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis_cluster:
    image: redis:7.2
    container_name: redis_cluster
    networks:
      network_redis_cluster:
        ipv4_address: 173.24.0.4
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        redis-cli --cluster create 173.24.0.1:6381 173.24.0.2:6382 173.24.0.3:6383 --cluster-replicas 1 --cluster-yes

    depends_on:
      - redis_1
      - redis_2
      - redis_3
